nginx:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php:php

php:
  image: php:7.2-fpm
  ports:
    - "9000:9000"
  volumes:
    - ./www/:/var/www/html/
    - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    - ./log/php-fpm/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql
    - redis:redis

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - ./conf/mysql/my.cnf:/etc/my.cnf:ro
    - ./mysql/:/var/lib/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: "123456"

memcache:
  image: memcached:latest
  ports:
    - "11211:11211"





